# Generated by Django 4.2.7 on 2023-11-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Coin İsmi')),
                ('symbol', models.CharField(max_length=50, verbose_name='Coin Sembolü')),
                ('image', models.CharField(max_length=200, verbose_name='Coin İconu')),
                ('current_price', models.CharField(max_length=50, verbose_name='Coin Güncel Fiyatı')),
                ('market_cap', models.CharField(max_length=100, verbose_name='Coin Hacmi')),
            ],
        ),
    ]
